### PR TITLE
Add append_geoid()

### PR DESCRIPTION
**Pull request by josiekre**
I think this takes care of #22. It is working for me anyway. I'm not sure I did the examples right. I'm calling dplyr chain so that might fail when building for CRAN. Also, let me know if you think the usability of it is weird. I implemented it so that it works like a dplyr verb. So one just calls

``` r
df %>% append_geoid()
```

And a new column gets added. The data frame must have `state`, `city`, and `street` columns. State needs to be state abbreviations.

I know this needs more error testing implemented, but that's the case for the whole package.

### CODE REVIEW

**Comment by gregmacfarlane** [comment]
I don't see right away where the travis check [fails](https://travis-ci.org/transportfoundry/censusr#L2425-L2435); it made it through your new examples okay.

**Comment by josiekre** [comment]
I am having a hard time understanding Travis output. I _think_ we are getting warnings rather than errors, but I can't figure out what the warnings are.

**Comment by josiekre** [comment]
I'm very confused.

**Comment by gregmacfarlane** [comment]
I'm confused too. I've moved your functions onto #25, let's close this PR and abandon.

**Pull request closed without merging**
